# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.1.4"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.box = "alpine/alpine64"
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]            
    v.memory = 512
  end
end
