# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_memory = 512
$vb_cpuexecutioncap = 25

Vagrant.require_version ">= 2.1.4"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.box = "alpine/alpine64"
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]            
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "#{$vb_cpuexecutioncap}"]
    v.memory = $vm_memory
  end
end
